import pickle
dict1={'1':'First  Location:  Placed where all DOWNLOADS are saved.  File Name: flag1.txt',
       '2':'Second  Location: Placed where all MUSIC are saved.  File Name: flag2.txt',
       '3':'Third  Location: Placed where all MEDIA devices are located.  File Name: flag3.txt',
       '4':'Fourth  Location: Placed where ROOT login is saved.  File Name: flag4.txt',
       '5':'Fifth  Location: Placed where all 32 Bit LIBRARY files are saved.  File Name: flag5.txt',
       '6':'Sixth  Location: Placed where we MOUNT our external devices.  File Name: flag6.txt',
       '7':'Seventh  Location: Placed where all TEMPORARY are saved.  File Name: flag7.txt'
       }
'''




'''
dictQ={
'7':'\nEach new term in the Fibonacci sequence is generated by adding the previous two terms.\n\
By starting with 0 and 1, the first 10 terms will be:\n\
0, 1, 1, 2, 3, 5, 8, 13, 21, 34 ...\nFind the 24th term in the fibonacci number.\n',
'1':'\nA string of eight binary digits is called ?\n',
'3':'\n1 megabits = __ Bytes ?\n',
'2':'\nWhich data structure follows FIFO  ?  \n',
'4':'\nThe sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.Find the sum of all the primes below 10,000.\n',
'6':'\nIf we list all the natural numbers below 10 that are multiples of 3 or 5,\nwe get 3, 5, 6 and 9. The sum of these multiples is 23.\n\
Find the sum of all the multiples of 3 or 5 below 1000.',
'5':'\nThe sum of the squares of the first ten natural numbers is,(1^2+2^2+...+10^2) = 385\n.The square of the sum of the first ten natural numbers is,\n(1+2+...+10)^2=3025\nHence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025−385=2640.\nFind the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.\n'
}
'''





'''
dictans={
         '1':'byte',
         '3':'125000',
         '2':'queue',
         '4':'5736396',
         '5':'25164150',
         '6':'233168',
         '7':'46368'
         }

dicthint={
    '1':'Hint : combination of bits\n',
    '3':'Hint : 1 megabit = 1000 kilobits ',
    '2':'Hint : Ends with e',
    '4':'Hint : Simple Prime number loop. Just need to add Sum variable.',
    '5':'Hint : Two diffrent loops, One for Sum of Squares, and other for square Of sum. Calculate their difference.',
    '6':'Hint : Use modulo operator for calculating multiples. Calculate their sum',
    '7':'Hint : 20th fibonacci number=6765, 21st is 10946'
    }

dictflag={
    '1':'CDAKJSHFNKJEL234GFLL9231BWFL1',
    '2':'OIJONKJBHBHJBUGBSDWE123FL2',
    '3':'HGRV2FVUYV213Y4UBUAHJOIEJDFL3',
    '4':'BLIV3EREJH3B554CU7HWBMLPOFL4',
    '5':'JDALSHFUIAHILEFBIASBCVAYUSBD',
    '6':'AWECBABVBAYWEBRUVBAUSBDHF23',
    '7':'NBNASD23BFUABUBAW5UBEBFUAWB'
    }

with open("Depend.pkl","wb") as file:
	pickle.dump(dict1,file)
	pickle.dump(dictQ,file)
	pickle.dump(dictans,file)
	pickle.dump(dicthint,file)
	pickle.dump(dictflag,file)
#CDAKJSHFNKJEL234GFLL9231BWFL1
#OIJONKJBHBHJBUGBSDWE123FL2
#HGRV2FVUYV213Y4UBUAHJOIEJDFL3
#BLIV3EREJH3B554CU7HWBMLPOFL4
#JDALSHFUIAHILEFBIASBCVAYUSBD
#AWECBABVBAYWEBRUVBAUSBDHF23
#NBNASD23BFUABUBAW5UBEBFUAWB


